[package]
name = "lox-space"
version = "0.0.0"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
lox_core.workspace = true
lox_time.workspace = true
