[package]
name = "lox-space"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "lox_space"
crate-type = ["lib", "cdylib"]

[dependencies]
lox-bodies = { workspace = true, features = ["python"] }
lox-coords.workspace = true
lox-time = { workspace = true, features = ["python"] }
lox-utils.workspace = true

pyo3.workspace = true

[[bench]]
name = "iau_frames"
harness = false

[[bench]]
name = "time_delta"
harness = false
