// SPDX-FileCopyrightText: 2026 Helge Eichhorn <git@helgeeichhorn.de>
//
// SPDX-License-Identifier: MPL-2.0

//! Parse and round-trip benchmarks for the KVN, XML, and JSON wire
//! formats across OPM, OEM, and OMM message kinds.
//!
//! Establishes a performance baseline so future changes can detect
//! regressions. Run with `cargo bench -p lox-odm`.

use divan::{Bencher, black_box};

fn main() {
    divan::main();
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const OPM_KVN: &str = "\
CCSDS_OPM_VERS = 3.0
COMMENT Generated by GSOC
CREATION_DATE = 2021-06-03T05:33:00.123
ORIGINATOR = GSOC
OBJECT_NAME = EUTELSAT W4
OBJECT_ID = 2021-028A
CENTER_NAME = EARTH
REF_FRAME = TOD
TIME_SYSTEM = UTC
EPOCH = 2021-06-03T00:00:00.000
X = 6655.9942 [km]
Y = -40218.5751 [km]
Z = -82.9177 [km]
X_DOT = 3.11548208 [km/s]
Y_DOT = 0.47042605 [km/s]
Z_DOT = -0.00101495 [km/s]
SEMI_MAJOR_AXIS = 41399.5123 [km]
ECCENTRICITY = 0.020842611
INCLINATION = 0.117746 [deg]
RA_OF_ASC_NODE = 17.604721 [deg]
ARG_OF_PERICENTER = 218.242943 [deg]
TRUE_ANOMALY = 41.922339 [deg]
GM = 398600.4415 [km**3/s**2]
MASS = 1913.000 [kg]
SOLAR_RAD_AREA = 10.000 [m**2]
SOLAR_RAD_COEFF = 1.300
DRAG_AREA = 10.000 [m**2]
DRAG_COEFF = 2.300
MAN_EPOCH_IGNITION = 2021-06-03T09:00:34.1
MAN_DURATION = 132.60 [s]
MAN_DELTA_MASS = -18.418 [kg]
MAN_REF_FRAME = EME2000
MAN_DV_1 = -0.02325700 [km/s]
MAN_DV_2 = 0.01683160 [km/s]
MAN_DV_3 = -0.00893444 [km/s]
";

const OEM_KVN: &str = "\
CCSDS_OEM_VERS = 3.0
CREATION_DATE = 1996-11-04T17:22:31
ORIGINATOR = NASA/JPL

META_START
OBJECT_NAME = MARS GLOBAL SURVEYOR
OBJECT_ID = 1996-062A
CENTER_NAME = MARS BARYCENTER
REF_FRAME = J2000
TIME_SYSTEM = TAI
START_TIME = 1996-12-18T12:00:00.331
STOP_TIME = 1996-12-28T21:28:00.331
INTERPOLATION = HERMITE
INTERPOLATION_DEGREE = 7
META_STOP

1996-12-18T12:00:00.331 2789.619 -280.045 -1746.755 4.73372 -2.49586 -1.04195
1996-12-18T12:01:00.331 2783.419 -308.143 -1877.071 5.18604 -2.42124 -1.99608
1996-12-18T12:02:00.331 2776.033 -336.859 -2008.682 5.63678 -2.33951 -1.94687
1996-12-28T21:28:00.331 -3881.024 563.959 -682.773 -3.28827 -3.66735 1.63861
";

const OMM_KVN: &str = "\
CCSDS_OMM_VERS = 3.0
CREATION_DATE = 2007-03-06T16:00:00
ORIGINATOR = NOAA/USA
OBJECT_NAME = GOES-13
OBJECT_ID = 2006-018A
CENTER_NAME = EARTH
REF_FRAME = TEME
TIME_SYSTEM = UTC
MEAN_ELEMENT_THEORY = SGP/SGP4
EPOCH = 2007-03-05T10:34:41.4264
SEMI_MAJOR_AXIS = 6655.9942 [km]
ECCENTRICITY = 0.0006703
INCLINATION = 51.6416 [deg]
RA_OF_ASC_NODE = 247.4627 [deg]
ARG_OF_PERICENTER = 130.5360 [deg]
MEAN_ANOMALY = 325.0288 [deg]
GM = 398600.8 [km**3/s**2]
EPHEMERIS_TYPE = 0
CLASSIFICATION_TYPE = U
NORAD_CAT_ID = 25544
ELEMENT_SET_NO = 999
REV_AT_EPOCH = 4453
BSTAR = 0.00011328
MEAN_MOTION_DOT = 0.00000264
MEAN_MOTION_DDOT = 0
";

const OPM_XML: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<opm id="CCSDS_OPM_VERS" version="3.0">
  <header><CREATION_DATE>2024-01-01T00:00:00</CREATION_DATE><ORIGINATOR>TEST</ORIGINATOR></header>
  <body><segment>
    <metadata><OBJECT_NAME>SAT</OBJECT_NAME><OBJECT_ID>2024-000A</OBJECT_ID><CENTER_NAME>EARTH</CENTER_NAME><REF_FRAME>ICRF</REF_FRAME><TIME_SYSTEM>TAI</TIME_SYSTEM></metadata>
    <data>
      <stateVector>
        <EPOCH>2024-01-01T00:00:00</EPOCH>
        <X units="km">7000.0</X><Y units="km">0.0</Y><Z units="km">0.0</Z>
        <X_DOT units="km/s">0.0</X_DOT><Y_DOT units="km/s">7.5</Y_DOT><Z_DOT units="km/s">0.0</Z_DOT>
      </stateVector>
    </data>
  </segment></body>
</opm>"#;

const OEM_XML: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<oem id="CCSDS_OEM_VERS" version="3.0">
  <header><CREATION_DATE>2024-01-01T00:00:00</CREATION_DATE><ORIGINATOR>TEST</ORIGINATOR></header>
  <body><segment>
    <metadata><OBJECT_NAME>SAT</OBJECT_NAME><OBJECT_ID>2024-000A</OBJECT_ID><CENTER_NAME>EARTH</CENTER_NAME><REF_FRAME>ICRF</REF_FRAME><TIME_SYSTEM>TAI</TIME_SYSTEM><START_TIME>2024-01-01T00:00:00</START_TIME><STOP_TIME>2024-01-01T00:01:00</STOP_TIME></metadata>
    <data>
      <stateVector><EPOCH>2024-01-01T00:00:00</EPOCH><X units="km">7000.0</X><Y units="km">0.0</Y><Z units="km">0.0</Z><X_DOT units="km/s">0.0</X_DOT><Y_DOT units="km/s">7.5</Y_DOT><Z_DOT units="km/s">0.0</Z_DOT></stateVector>
      <stateVector><EPOCH>2024-01-01T00:01:00</EPOCH><X units="km">7001.0</X><Y units="km">0.0</Y><Z units="km">0.0</Z><X_DOT units="km/s">0.0</X_DOT><Y_DOT units="km/s">7.5</Y_DOT><Z_DOT units="km/s">0.0</Z_DOT></stateVector>
    </data>
  </segment></body>
</oem>"#;

const OMM_JSON: &str = r#"{
    "CCSDS_OMM_VERS": "2.0",
    "CREATION_DATE": "2020-12-29T06:26:10",
    "ORIGINATOR": "18 SPCS",
    "OBJECT_NAME": "NUSAT-8",
    "OBJECT_ID": "2020-003C",
    "CENTER_NAME": "EARTH",
    "REF_FRAME": "TEME",
    "TIME_SYSTEM": "UTC",
    "MEAN_ELEMENT_THEORY": "SGP4",
    "EPOCH": "2020-12-29T03:57:59.406624",
    "MEAN_MOTION": "15.27989249",
    "ECCENTRICITY": "0.00133560",
    "INCLINATION": "97.2970",
    "RA_OF_ASC_NODE": "66.4161",
    "ARG_OF_PERICENTER": "110.6345",
    "MEAN_ANOMALY": "334.7107",
    "NORAD_CAT_ID": "45018",
    "BSTAR": "0.0000845530"
}"#;

// ---------------------------------------------------------------------------
// KVN benches
// ---------------------------------------------------------------------------

#[divan::bench]
fn kvn_parse_opm(bencher: Bencher) {
    bencher.bench(|| lox_odm::kvn::read_opm(black_box(OPM_KVN)).unwrap());
}

#[divan::bench]
fn kvn_parse_oem(bencher: Bencher) {
    bencher.bench(|| lox_odm::kvn::read_oem(black_box(OEM_KVN)).unwrap());
}

#[divan::bench]
fn kvn_parse_omm(bencher: Bencher) {
    bencher.bench(|| lox_odm::kvn::read_omm(black_box(OMM_KVN)).unwrap());
}

#[divan::bench]
fn kvn_round_trip_opm(bencher: Bencher) {
    let opm = lox_odm::kvn::read_opm(OPM_KVN).unwrap();
    bencher.bench(|| {
        let s = lox_odm::kvn::write_opm(black_box(&opm));
        lox_odm::kvn::read_opm(&s).unwrap()
    });
}

#[divan::bench]
fn kvn_round_trip_oem(bencher: Bencher) {
    let oem = lox_odm::kvn::read_oem(OEM_KVN).unwrap();
    bencher.bench(|| {
        let s = lox_odm::kvn::write_oem(black_box(&oem));
        lox_odm::kvn::read_oem(&s).unwrap()
    });
}

#[divan::bench]
fn kvn_round_trip_omm(bencher: Bencher) {
    let omm = lox_odm::kvn::read_omm(OMM_KVN).unwrap();
    bencher.bench(|| {
        let s = lox_odm::kvn::write_omm(black_box(&omm));
        lox_odm::kvn::read_omm(&s).unwrap()
    });
}

// ---------------------------------------------------------------------------
// XML benches
// ---------------------------------------------------------------------------

#[divan::bench]
fn xml_parse_opm(bencher: Bencher) {
    bencher.bench(|| lox_odm::xml::read_opm(black_box(OPM_XML)).unwrap());
}

#[divan::bench]
fn xml_parse_oem(bencher: Bencher) {
    bencher.bench(|| lox_odm::xml::read_oem(black_box(OEM_XML)).unwrap());
}

#[divan::bench]
fn xml_round_trip_opm(bencher: Bencher) {
    let opm = lox_odm::xml::read_opm(OPM_XML).unwrap();
    bencher.bench(|| {
        let s = lox_odm::xml::write_opm(black_box(&opm));
        lox_odm::xml::read_opm(&s).unwrap()
    });
}

#[divan::bench]
fn xml_round_trip_oem(bencher: Bencher) {
    let oem = lox_odm::xml::read_oem(OEM_XML).unwrap();
    bencher.bench(|| {
        let s = lox_odm::xml::write_oem(black_box(&oem));
        lox_odm::xml::read_oem(&s).unwrap()
    });
}

// ---------------------------------------------------------------------------
// JSON benches (OMM only)
// ---------------------------------------------------------------------------

#[divan::bench]
fn json_parse_omm(bencher: Bencher) {
    bencher.bench(|| lox_odm::json::read_omm(black_box(OMM_JSON)).unwrap());
}

#[divan::bench]
fn json_round_trip_omm(bencher: Bencher) {
    let omm = lox_odm::json::read_omm(OMM_JSON).unwrap();
    bencher.bench(|| {
        let s = lox_odm::json::write_omm(black_box(&omm));
        lox_odm::json::read_omm(&s).unwrap()
    });
}

// ---------------------------------------------------------------------------
// Top-level auto-detecting reads
// ---------------------------------------------------------------------------

#[divan::bench]
fn detect_kvn_opm(bencher: Bencher) {
    bencher.bench(|| lox_odm::read_opm(black_box(OPM_KVN)).unwrap());
}

#[divan::bench]
fn detect_xml_opm(bencher: Bencher) {
    bencher.bench(|| lox_odm::read_opm(black_box(OPM_XML)).unwrap());
}

#[divan::bench]
fn detect_json_omm(bencher: Bencher) {
    bencher.bench(|| lox_odm::read_omm(black_box(OMM_JSON)).unwrap());
}
