// SPDX-FileCopyrightText: 2026 Helge Eichhorn <git@helgeeichhorn.de>
//
// SPDX-License-Identifier: MPL-2.0

//! Canonical KVN writer.
//!
//! Implements [`Display`] for [`KvnDocument`] and recursively for its
//! sub-structures. The writer normalises whitespace and casing for
//! semantic-lossless round-trip.

use std::fmt::{self, Display, Formatter};

use crate::kvn::ast::{KvnDocument, KvnEntry, KvnField, KvnRow, KvnSection};
use crate::types::common::MessageKind;

impl Display for KvnDocument {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        // Preamble comments (rare — banner lines above the version header).
        for comment in &self.preamble {
            writeln!(f, "COMMENT {comment}")?;
        }
        // Header line: CCSDS_<KIND>_VERS = <version>
        let kind_token = match self.message_kind {
            MessageKind::Opm => "OPM",
            MessageKind::Oem => "OEM",
            MessageKind::Omm => "OMM",
            MessageKind::Ocm => "OCM",
        };
        writeln!(f, "CCSDS_{kind_token}_VERS = {}", self.version)?;

        for (idx, section) in self.sections.iter().enumerate() {
            // Blank line between top-level sections (but not before the first).
            if idx > 0 {
                writeln!(f)?;
            }
            write_section(f, section)?;
        }
        Ok(())
    }
}

fn write_section(f: &mut Formatter<'_>, section: &KvnSection) -> fmt::Result {
    if section.bracketed {
        writeln!(f, "{}_START", section.keyword)?;
    }
    for entry in &section.entries {
        write_entry(f, entry)?;
    }
    if section.bracketed {
        writeln!(f, "{}_STOP", section.keyword)?;
    }
    Ok(())
}

fn write_entry(f: &mut Formatter<'_>, entry: &KvnEntry) -> fmt::Result {
    match entry {
        KvnEntry::Field(field) => write_field(f, field),
        KvnEntry::Row(row) => write_row(f, row),
        KvnEntry::Subsection(section) => write_section(f, section),
        KvnEntry::Comment(text) => writeln!(f, "COMMENT {text}"),
    }
}

fn write_field(f: &mut Formatter<'_>, field: &KvnField) -> fmt::Result {
    match &field.unit {
        Some(unit) => writeln!(f, "{} = {} [{unit}]", field.key, field.value),
        None => writeln!(f, "{} = {}", field.key, field.value),
    }
}

fn write_row(f: &mut Formatter<'_>, row: &KvnRow) -> fmt::Result {
    let joined = row.values.join(" ");
    writeln!(f, "{joined}")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn opm_doc(sections: Vec<KvnSection>) -> KvnDocument {
        KvnDocument {
            message_kind: MessageKind::Opm,
            version: "3.0".to_string(),
            preamble: Vec::new(),
            sections,
        }
    }

    fn field(key: &str, value: &str) -> KvnEntry {
        KvnEntry::Field(KvnField {
            key: key.to_string(),
            value: value.to_string(),
            unit: None,
        })
    }

    fn field_with_unit(key: &str, value: &str, unit: &str) -> KvnEntry {
        KvnEntry::Field(KvnField {
            key: key.to_string(),
            value: value.to_string(),
            unit: Some(unit.to_string()),
        })
    }

    fn comment(text: &str) -> KvnEntry {
        KvnEntry::Comment(text.to_string())
    }

    #[test]
    fn empty_opm_emits_only_version_header() {
        let doc = opm_doc(Vec::new());
        assert_eq!(format!("{doc}"), "CCSDS_OPM_VERS = 3.0\n");
    }

    #[test]
    fn preamble_comments_emit_before_version_header() {
        let doc = KvnDocument {
            message_kind: MessageKind::Opm,
            version: "3.0".to_string(),
            preamble: vec!["Generated by ABC".to_string(), "v1.2.3".to_string()],
            sections: Vec::new(),
        };
        let expected = "COMMENT Generated by ABC\n\
                        COMMENT v1.2.3\n\
                        CCSDS_OPM_VERS = 3.0\n";
        assert_eq!(format!("{doc}"), expected);
    }

    #[test]
    fn header_section_emits_fields_without_start_stop() {
        let doc = opm_doc(vec![KvnSection {
            keyword: "HEADER".to_string(),
            bracketed: false,
            entries: vec![
                field("CREATION_DATE", "2024-01-01T00:00:00"),
                field("ORIGINATOR", "TEST"),
            ],
        }]);
        let expected = "CCSDS_OPM_VERS = 3.0\n\
                        CREATION_DATE = 2024-01-01T00:00:00\n\
                        ORIGINATOR = TEST\n";
        assert_eq!(format!("{doc}"), expected);
    }

    #[test]
    fn bracketed_section_emits_start_stop_markers() {
        let doc = opm_doc(vec![KvnSection {
            keyword: "META".to_string(),
            bracketed: true,
            entries: vec![field("OBJECT_NAME", "ISS")],
        }]);
        let expected = "CCSDS_OPM_VERS = 3.0\n\
                        META_START\n\
                        OBJECT_NAME = ISS\n\
                        META_STOP\n";
        assert_eq!(format!("{doc}"), expected);
    }

    #[test]
    fn field_with_unit_renders_brackets() {
        let doc = opm_doc(vec![KvnSection {
            keyword: "DATA".to_string(),
            bracketed: false,
            entries: vec![field_with_unit("X", "7000.0", "km")],
        }]);
        let expected = "CCSDS_OPM_VERS = 3.0\n\
                        X = 7000.0 [km]\n";
        assert_eq!(format!("{doc}"), expected);
    }

    #[test]
    fn comment_entry_emits_inline_at_its_position() {
        let doc = opm_doc(vec![KvnSection {
            keyword: "DATA".to_string(),
            bracketed: false,
            entries: vec![
                field_with_unit("X", "7000.0", "km"),
                comment("operator estimate"),
                field_with_unit("Y", "0.0", "km"),
            ],
        }]);
        let expected = "CCSDS_OPM_VERS = 3.0\n\
                        X = 7000.0 [km]\n\
                        COMMENT operator estimate\n\
                        Y = 0.0 [km]\n";
        assert_eq!(format!("{doc}"), expected);
    }

    #[test]
    fn comment_at_section_start_emits_before_first_field() {
        let doc = opm_doc(vec![KvnSection {
            keyword: "META".to_string(),
            bracketed: true,
            entries: vec![comment("Reference orbit"), field("OBJECT_NAME", "ISS")],
        }]);
        let expected = "CCSDS_OPM_VERS = 3.0\n\
                        META_START\n\
                        COMMENT Reference orbit\n\
                        OBJECT_NAME = ISS\n\
                        META_STOP\n";
        assert_eq!(format!("{doc}"), expected);
    }

    #[test]
    fn ephemeris_row_emits_space_separated() {
        let doc = KvnDocument {
            message_kind: MessageKind::Oem,
            version: "3.0".to_string(),
            preamble: Vec::new(),
            sections: vec![KvnSection {
                keyword: "DATA".to_string(),
                bracketed: false,
                entries: vec![KvnEntry::Row(KvnRow {
                    values: vec![
                        "2024-01-01T00:00:00".to_string(),
                        "7000.0".to_string(),
                        "0.0".to_string(),
                        "0.0".to_string(),
                        "0.0".to_string(),
                        "7.5".to_string(),
                        "0.0".to_string(),
                    ],
                })],
            }],
        };
        let expected = "CCSDS_OEM_VERS = 3.0\n\
                        2024-01-01T00:00:00 7000.0 0.0 0.0 0.0 7.5 0.0\n";
        assert_eq!(format!("{doc}"), expected);
    }

    #[test]
    fn nested_subsection_renders_inline_in_parent() {
        let doc = opm_doc(vec![KvnSection {
            keyword: "DATA".to_string(),
            bracketed: false,
            entries: vec![KvnEntry::Subsection(KvnSection {
                keyword: "MANEUVER".to_string(),
                bracketed: false,
                entries: vec![field("MAN_EPOCH_IGNITION", "2024-01-02T00:00:00")],
            })],
        }]);
        let expected = "CCSDS_OPM_VERS = 3.0\n\
                        MAN_EPOCH_IGNITION = 2024-01-02T00:00:00\n";
        assert_eq!(format!("{doc}"), expected);
    }

    #[test]
    fn multiple_top_level_sections_separated_by_blank_line() {
        let doc = opm_doc(vec![
            KvnSection {
                keyword: "HEADER".to_string(),
                bracketed: false,
                entries: vec![field("ORIGINATOR", "TEST")],
            },
            KvnSection {
                keyword: "META".to_string(),
                bracketed: true,
                entries: vec![field("OBJECT_NAME", "ISS")],
            },
        ]);
        let expected = "CCSDS_OPM_VERS = 3.0\n\
                        ORIGINATOR = TEST\n\
                        \n\
                        META_START\n\
                        OBJECT_NAME = ISS\n\
                        META_STOP\n";
        assert_eq!(format!("{doc}"), expected);
    }
}
