[package]
name = "lox-bodies"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lox-time.workspace = true
lox-utils.workspace = true

dyn-clone.workspace = true
fast_polynomial.workspace = true
thiserror.workspace = true

[dev-dependencies]
float_eq.workspace = true
