# SPDX-FileCopyrightText: 2024 Andrei Zisu <matzipan@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

ignore:
  # This code is tested indirectly with high coverage but coverage tools don't
  # handle proc macros
  - "crates/lox-derive/src/lib.rs"
  