[package]
name = "lox-test-utils"
version = "0.1.0-alpha.0"
description = "Testing utilities for the Lox ecosystem"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
