use proc_macro2::TokenStream;
use std::fs;
use std::path::Path;

pub const COPYRIGHT_NOTICE: &str = "/*
 * Copyright (c) 2024. Helge Eichhorn and the LOX contributors
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 */\n\n";

pub const AUTO_GENERATION_NOTICE: &str = "// Auto-generated by `lox-gen`. Do not edit!\n\n";

pub fn format(ts: TokenStream) -> String {
    let file = syn::parse2(ts).unwrap();
    prettyplease::unparse(&file)
}

pub fn write_file(dir: &Path, file: &str, code: TokenStream) {
    let mut module = String::from(COPYRIGHT_NOTICE);
    module.push_str(AUTO_GENERATION_NOTICE);
    module.push_str(&format(code));

    let out = dir.join(file);
    fs::write(&out, module).expect("file should be writeable");
}
