// SPDX-FileCopyrightText: 2023 Andrei Zisu <matzipan@gmail.com>
// SPDX-FileCopyrightText: 2023 Helge Eichhorn <git@helgeeichhorn.de>
// SPDX-FileCopyrightText: 2024 Angus Morrison <github@angus-morrison.com>
// SPDX-License-Identifier: MPL-2.0

use proc_macro2::TokenStream;
use std::fs;
use std::path::Path;
use std::process::Command;

pub const COPYRIGHT_NOTICE: &str =
    "// SPDX-FileCopyrightText: 2024 Helge Eichhorn <git@helgeeichhorn.de>
// SPDX-License-Identifier: MPL-2.0

";

pub const AUTO_GENERATION_NOTICE: &str = "// Auto-generated by `lox-gen`. Do not edit!\n\n";

pub fn write_file(dir: &Path, file: &str, code: TokenStream) {
    let mut module = String::from(COPYRIGHT_NOTICE);
    module.push_str(AUTO_GENERATION_NOTICE);
    module.push_str(code.to_string().as_str());

    let out = dir.join(file);
    fs::write(&out, module).expect("file should be writeable");

    Command::new("rustfmt")
        .args([out.to_str().unwrap()])
        .status()
        .expect("formatting should work");
}
