// SPDX-FileCopyrightText: 2026 Helge Eichhorn <git@helgeeichhorn.de>
//
// SPDX-License-Identifier: MPL-2.0

//! Integration tests: XML OEM round-trip on realistic fixtures and synthetic
//! inputs, verifying that parse → write → re-parse produces structurally
//! identical values.

use lox_odm::xml::oem::{read_oem, write_oem};

// A realistic single-segment OEM fixture modelled after CCSDS 502.0-B-3
// example messages.  Uses TAI time system with ISO 8601 timestamps.
const SINGLE_SEGMENT_FIXTURE: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<oem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="http://sanaregistry.org/r/ndmxml/ndmxml-1.0-master.xsd"
     id="CCSDS_OEM_VERS" version="3.0">
    <header>
        <COMMENT>OEM integration test fixture</COMMENT>
        <CREATION_DATE>2024-01-15T10:00:00</CREATION_DATE>
        <ORIGINATOR>TEST-ORG</ORIGINATOR>
        <MESSAGE_ID>OEM-TEST-001</MESSAGE_ID>
    </header>
    <body>
        <segment>
            <metadata>
                <COMMENT>LEO segment</COMMENT>
                <OBJECT_NAME>TEST-SAT</OBJECT_NAME>
                <OBJECT_ID>2024-001A</OBJECT_ID>
                <CENTER_NAME>EARTH</CENTER_NAME>
                <REF_FRAME>EME2000</REF_FRAME>
                <TIME_SYSTEM>TAI</TIME_SYSTEM>
                <START_TIME>2024-01-15T12:00:00.000</START_TIME>
                <STOP_TIME>2024-01-15T12:10:00.000</STOP_TIME>
                <INTERPOLATION>HERMITE</INTERPOLATION>
                <INTERPOLATION_DEGREE>7</INTERPOLATION_DEGREE>
            </metadata>
            <data>
                <COMMENT>Generated by test suite</COMMENT>
                <stateVector>
                    <EPOCH>2024-01-15T12:00:00.000</EPOCH>
                    <X units="km">6878.137</X>
                    <Y units="km">0.000</Y>
                    <Z units="km">0.000</Z>
                    <X_DOT units="km/s">0.000</X_DOT>
                    <Y_DOT units="km/s">7.784</Y_DOT>
                    <Z_DOT units="km/s">0.000</Z_DOT>
                </stateVector>
                <stateVector>
                    <EPOCH>2024-01-15T12:02:00.000</EPOCH>
                    <X units="km">6705.423</X>
                    <Y units="km">1456.291</Y>
                    <Z units="km">0.000</Z>
                    <X_DOT units="km/s">-1.597</X_DOT>
                    <Y_DOT units="km/s">7.617</Y_DOT>
                    <Z_DOT units="km/s">0.000</Z_DOT>
                </stateVector>
                <stateVector>
                    <EPOCH>2024-01-15T12:04:00.000</EPOCH>
                    <X units="km">6207.431</X>
                    <Y units="km">2832.719</Y>
                    <Z units="km">0.000</Z>
                    <X_DOT units="km/s">-3.104</X_DOT>
                    <Y_DOT units="km/s">7.111</Y_DOT>
                    <Z_DOT units="km/s">0.000</Z_DOT>
                </stateVector>
                <stateVector>
                    <EPOCH>2024-01-15T12:06:00.000</EPOCH>
                    <X units="km">5418.327</X>
                    <Y units="km">4068.214</Y>
                    <Z units="km">0.000</Z>
                    <X_DOT units="km/s">-4.462</X_DOT>
                    <Y_DOT units="km/s">6.292</Y_DOT>
                    <Z_DOT units="km/s">0.000</Z_DOT>
                </stateVector>
            </data>
        </segment>
    </body>
</oem>"#;

// A multi-segment OEM fixture: two segments with different center bodies,
// modelling an interplanetary trajectory handover.
const MULTI_SEGMENT_FIXTURE: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<oem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="http://sanaregistry.org/r/ndmxml/ndmxml-1.0-master.xsd"
     id="CCSDS_OEM_VERS" version="3.0">
    <header>
        <CREATION_DATE>2024-03-01T00:00:00</CREATION_DATE>
        <ORIGINATOR>MISSION-CTRL</ORIGINATOR>
    </header>
    <body>
        <segment>
            <metadata>
                <OBJECT_NAME>EXPLORER-1</OBJECT_NAME>
                <OBJECT_ID>2024-010A</OBJECT_ID>
                <CENTER_NAME>EARTH</CENTER_NAME>
                <REF_FRAME>ICRF</REF_FRAME>
                <TIME_SYSTEM>TAI</TIME_SYSTEM>
                <START_TIME>2024-03-01T06:00:00.000</START_TIME>
                <STOP_TIME>2024-03-01T08:00:00.000</STOP_TIME>
            </metadata>
            <data>
                <stateVector>
                    <EPOCH>2024-03-01T06:00:00.000</EPOCH>
                    <X units="km">6878.0</X>
                    <Y units="km">100.0</Y>
                    <Z units="km">50.0</Z>
                    <X_DOT units="km/s">0.5</X_DOT>
                    <Y_DOT units="km/s">7.7</Y_DOT>
                    <Z_DOT units="km/s">0.1</Z_DOT>
                </stateVector>
                <stateVector>
                    <EPOCH>2024-03-01T07:00:00.000</EPOCH>
                    <X units="km">5100.0</X>
                    <Y units="km">4500.0</Y>
                    <Z units="km">200.0</Z>
                    <X_DOT units="km/s">-4.0</X_DOT>
                    <Y_DOT units="km/s">6.1</Y_DOT>
                    <Z_DOT units="km/s">0.2</Z_DOT>
                </stateVector>
                <stateVector>
                    <EPOCH>2024-03-01T08:00:00.000</EPOCH>
                    <X units="km">2200.0</X>
                    <Y units="km">6600.0</Y>
                    <Z units="km">300.0</Z>
                    <X_DOT units="km/s">-6.5</X_DOT>
                    <Y_DOT units="km/s">3.0</Y_DOT>
                    <Z_DOT units="km/s">0.1</Z_DOT>
                </stateVector>
            </data>
        </segment>
        <segment>
            <metadata>
                <OBJECT_NAME>EXPLORER-1</OBJECT_NAME>
                <OBJECT_ID>2024-010A</OBJECT_ID>
                <CENTER_NAME>MOON</CENTER_NAME>
                <REF_FRAME>ICRF</REF_FRAME>
                <TIME_SYSTEM>TAI</TIME_SYSTEM>
                <START_TIME>2024-03-02T00:00:00.000</START_TIME>
                <STOP_TIME>2024-03-02T06:00:00.000</STOP_TIME>
            </metadata>
            <data>
                <stateVector>
                    <EPOCH>2024-03-02T00:00:00.000</EPOCH>
                    <X units="km">1837.4</X>
                    <Y units="km">0.0</Y>
                    <Z units="km">0.0</Z>
                    <X_DOT units="km/s">0.0</X_DOT>
                    <Y_DOT units="km/s">1.68</Y_DOT>
                    <Z_DOT units="km/s">0.0</Z_DOT>
                </stateVector>
                <stateVector>
                    <EPOCH>2024-03-02T03:00:00.000</EPOCH>
                    <X units="km">-920.5</X>
                    <Y units="km">1593.8</Y>
                    <Z units="km">0.0</Z>
                    <X_DOT units="km/s">-1.455</X_DOT>
                    <Y_DOT units="km/s">-0.840</Y_DOT>
                    <Z_DOT units="km/s">0.0</Z_DOT>
                </stateVector>
            </data>
        </segment>
    </body>
</oem>"#;

// An OEM fixture with a covariance history block.
const COVARIANCE_FIXTURE: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<oem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="http://sanaregistry.org/r/ndmxml/ndmxml-1.0-master.xsd"
     id="CCSDS_OEM_VERS" version="3.0">
    <header>
        <CREATION_DATE>2024-06-01T00:00:00</CREATION_DATE>
        <ORIGINATOR>COV-TEST</ORIGINATOR>
    </header>
    <body>
        <segment>
            <metadata>
                <OBJECT_NAME>COV-SAT</OBJECT_NAME>
                <OBJECT_ID>2024-099A</OBJECT_ID>
                <CENTER_NAME>EARTH</CENTER_NAME>
                <REF_FRAME>EME2000</REF_FRAME>
                <TIME_SYSTEM>TAI</TIME_SYSTEM>
                <START_TIME>2024-06-01T12:00:00.000</START_TIME>
                <STOP_TIME>2024-06-01T12:30:00.000</STOP_TIME>
            </metadata>
            <data>
                <stateVector>
                    <EPOCH>2024-06-01T12:00:00.000</EPOCH>
                    <X units="km">6878.137</X>
                    <Y units="km">0.000</Y>
                    <Z units="km">0.000</Z>
                    <X_DOT units="km/s">0.000</X_DOT>
                    <Y_DOT units="km/s">7.784</Y_DOT>
                    <Z_DOT units="km/s">0.000</Z_DOT>
                </stateVector>
                <stateVector>
                    <EPOCH>2024-06-01T12:15:00.000</EPOCH>
                    <X units="km">4115.382</X>
                    <Y units="km">5380.415</Y>
                    <Z units="km">0.000</Z>
                    <X_DOT units="km/s">-5.905</X_DOT>
                    <Y_DOT units="km/s">4.513</Y_DOT>
                    <Z_DOT units="km/s">0.000</Z_DOT>
                </stateVector>
                <covarianceMatrix>
                    <COMMENT>Covariance at T+0</COMMENT>
                    <EPOCH>2024-06-01T12:00:00.000</EPOCH>
                    <COV_REF_FRAME>EME2000</COV_REF_FRAME>
                    <CX_X>3.3e-04</CX_X>
                    <CY_X>4.6e-04</CY_X>
                    <CY_Y>8.1e-04</CY_Y>
                    <CZ_X>0.0</CZ_X>
                    <CZ_Y>0.0</CZ_Y>
                    <CZ_Z>1.2e-04</CZ_Z>
                    <CX_DOT_X>2.4e-07</CX_DOT_X>
                    <CX_DOT_Y>3.1e-07</CX_DOT_Y>
                    <CX_DOT_Z>0.0</CX_DOT_Z>
                    <CX_DOT_X_DOT>1.8e-10</CX_DOT_X_DOT>
                    <CY_DOT_X>3.1e-07</CY_DOT_X>
                    <CY_DOT_Y>5.4e-07</CY_DOT_Y>
                    <CY_DOT_Z>0.0</CY_DOT_Z>
                    <CY_DOT_X_DOT>2.5e-10</CY_DOT_X_DOT>
                    <CY_DOT_Y_DOT>4.9e-10</CY_DOT_Y_DOT>
                    <CZ_DOT_X>0.0</CZ_DOT_X>
                    <CZ_DOT_Y>0.0</CZ_DOT_Y>
                    <CZ_DOT_Z>1.0e-07</CZ_DOT_Z>
                    <CZ_DOT_X_DOT>0.0</CZ_DOT_X_DOT>
                    <CZ_DOT_Y_DOT>0.0</CZ_DOT_Y_DOT>
                    <CZ_DOT_Z_DOT>9.0e-11</CZ_DOT_Z_DOT>
                </covarianceMatrix>
                <covarianceMatrix>
                    <EPOCH>2024-06-01T12:15:00.000</EPOCH>
                    <CX_X>5.1e-04</CX_X>
                    <CY_X>6.2e-04</CY_X>
                    <CY_Y>9.3e-04</CY_Y>
                    <CZ_X>0.0</CZ_X>
                    <CZ_Y>0.0</CZ_Y>
                    <CZ_Z>1.5e-04</CZ_Z>
                    <CX_DOT_X>3.0e-07</CX_DOT_X>
                    <CX_DOT_Y>4.0e-07</CX_DOT_Y>
                    <CX_DOT_Z>0.0</CX_DOT_Z>
                    <CX_DOT_X_DOT>2.2e-10</CX_DOT_X_DOT>
                    <CY_DOT_X>4.0e-07</CY_DOT_X>
                    <CY_DOT_Y>6.1e-07</CY_DOT_Y>
                    <CY_DOT_Z>0.0</CY_DOT_Z>
                    <CY_DOT_X_DOT>3.0e-10</CY_DOT_X_DOT>
                    <CY_DOT_Y_DOT>5.8e-10</CY_DOT_Y_DOT>
                    <CZ_DOT_X>0.0</CZ_DOT_X>
                    <CZ_DOT_Y>0.0</CZ_DOT_Y>
                    <CZ_DOT_Z>1.2e-07</CZ_DOT_Z>
                    <CZ_DOT_X_DOT>0.0</CZ_DOT_X_DOT>
                    <CZ_DOT_Y_DOT>0.0</CZ_DOT_Y_DOT>
                    <CZ_DOT_Z_DOT>1.1e-10</CZ_DOT_Z_DOT>
                </covarianceMatrix>
            </data>
        </segment>
    </body>
</oem>"#;

// -----------------------------------------------------------------------
// 1. Double round-trip on the realistic single-segment fixture
//    First parse normalises epoch string precision; after that the two
//    consecutive parses must agree structurally.
// -----------------------------------------------------------------------

#[test]
fn single_segment_fixture_ast_round_trip() {
    let first = read_oem(SINGLE_SEGMENT_FIXTURE).expect("first parse failed");
    let serialised = write_oem(&first).unwrap();
    let second = read_oem(&serialised).expect("second parse failed");
    let serialised2 = write_oem(&second).unwrap();
    let third = read_oem(&serialised2).expect("third parse failed");
    assert_eq!(second, third, "double round-trip mismatch");
}

// -----------------------------------------------------------------------
// 2. Multi-segment count and per-segment state count
// -----------------------------------------------------------------------

#[test]
fn multi_segment_count_and_state_count() {
    let oem = read_oem(MULTI_SEGMENT_FIXTURE).expect("parse failed");
    assert_eq!(oem.segments.len(), 2, "expected 2 segments");
    assert_eq!(
        oem.segments[0].states.len(),
        3,
        "segment 0: expected 3 states"
    );
    assert_eq!(
        oem.segments[1].states.len(),
        2,
        "segment 1: expected 2 states"
    );

    // Center body correctly parsed for each segment
    assert_eq!(
        oem.segments[0].metadata.center,
        lox_odm::types::common::OdmCenter::Known(lox_bodies::DynOrigin::Earth)
    );
    assert_eq!(
        oem.segments[1].metadata.center,
        lox_odm::types::common::OdmCenter::Known(lox_bodies::DynOrigin::Moon)
    );

    // Double round-trip stable
    let serialised = write_oem(&oem).unwrap();
    let second = read_oem(&serialised).expect("second parse failed");
    let serialised2 = write_oem(&second).unwrap();
    let third = read_oem(&serialised2).expect("third parse failed");
    assert_eq!(second, third, "multi-segment double round-trip mismatch");
}

// -----------------------------------------------------------------------
// 3. Covariance round-trip with structural equality
// -----------------------------------------------------------------------

#[test]
fn covariance_fixture_round_trip_structural_equality() {
    let first = read_oem(COVARIANCE_FIXTURE).expect("first parse failed");

    // Basic structure checks
    assert_eq!(first.segments.len(), 1);
    assert_eq!(first.segments[0].states.len(), 2);
    assert_eq!(
        first.segments[0].covariance_history.len(),
        2,
        "expected 2 covariance entries"
    );

    // First covariance: has comment, has COV_REF_FRAME
    let cov0 = &first.segments[0].covariance_history[0];
    assert_eq!(cov0.comments, vec!["Covariance at T+0".to_string()]);
    assert!(cov0.frame.is_some(), "first covariance should have a frame");
    let diff_cx_x = (cov0.matrix[(0, 0)] - 3.3e-04).abs();
    assert!(
        diff_cx_x < 1e-12,
        "CX_X unexpected: {}",
        cov0.matrix[(0, 0)]
    );

    // Second covariance: no comment, no COV_REF_FRAME
    let cov1 = &first.segments[0].covariance_history[1];
    assert!(cov1.comments.is_empty(), "second covariance has no comment");
    assert!(cov1.frame.is_none(), "second covariance has no frame");
    let diff_cx_x1 = (cov1.matrix[(0, 0)] - 5.1e-04).abs();
    assert!(
        diff_cx_x1 < 1e-12,
        "second CX_X unexpected: {}",
        cov1.matrix[(0, 0)]
    );

    // Matrix symmetry preserved
    assert_eq!(cov0.matrix[(1, 0)], cov0.matrix[(0, 1)]);
    assert_eq!(cov0.matrix[(3, 0)], cov0.matrix[(0, 3)]);

    // Double round-trip: matrices must be identical
    let serialised = write_oem(&first).unwrap();
    let second = read_oem(&serialised).expect("second parse failed");
    let serialised2 = write_oem(&second).unwrap();
    let third = read_oem(&serialised2).expect("third parse failed");

    let cov0_r3 = &third.segments[0].covariance_history[0];
    let cov1_r3 = &third.segments[0].covariance_history[1];
    assert_eq!(
        cov0.matrix, cov0_r3.matrix,
        "first covariance matrix changed across round-trip"
    );
    assert_eq!(
        cov1.matrix, cov1_r3.matrix,
        "second covariance matrix changed across round-trip"
    );
}

// -----------------------------------------------------------------------
// 4. Single-segment state values preserved with km↔m conversion
// -----------------------------------------------------------------------

#[test]
fn single_segment_state_values_preserved() {
    let oem = read_oem(SINGLE_SEGMENT_FIXTURE).expect("parse failed");
    let seg = &oem.segments[0];
    assert_eq!(seg.states.len(), 4);

    // First state: X=6878.137 km → 6878137.0 m internally
    let (_, state0) = &seg.states[0];
    let pos0 = state0.position();
    let diff_x = (pos0.x - 6_878_137.0).abs();
    assert!(diff_x < 1.0, "X[0] unexpected: {}", pos0.x);

    // Second state: Y_DOT=7.617 km/s → 7617.0 m/s
    let (_, state1) = &seg.states[1];
    let vel1 = state1.velocity();
    let diff_ydot = (vel1.y - 7617.0).abs();
    assert!(diff_ydot < 1.0, "Y_DOT[1] unexpected: {}", vel1.y);

    // Metadata fields preserved
    assert_eq!(seg.metadata.object_name, "TEST-SAT");
    assert_eq!(seg.metadata.object_id, "2024-001A");
    assert_eq!(seg.metadata.interpolation.as_deref(), Some("HERMITE"));
    assert_eq!(seg.metadata.interpolation_degree, Some(7));
}
