// SPDX-FileCopyrightText: 2026 Helge Eichhorn <git@helgeeichhorn.de>
//
// SPDX-License-Identifier: MPL-2.0

//! End-to-end round-trip tests for the KVN OPM reader/writer against a
//! realistic operator-formatted fixture (a GSOC AMF-3 OPM with
//! Keplerian elements, spacecraft parameters, and two maneuvers).
//!
//! These exercise the public API: [`lox_odm::kvn::parse`],
//! [`lox_odm::kvn::read_opm`], [`lox_odm::kvn::write_opm`], plus
//! [`std::fmt::Display`] on [`lox_odm::kvn::KvnDocument`].

use lox_odm::kvn::{parse, read_opm, write_opm};

const GSOC_OPM: &str = "\
CCSDS_OPM_VERS = 3.0
COMMENT Generated by GSOC, R. Kiehling
COMMENT Current intermediate orbit IO2 and maneuver planning data
CREATION_DATE = 2021-06-03T05:33:00.123
ORIGINATOR = GSOC
OBJECT_NAME = EUTELSAT W4
OBJECT_ID = 2021-028A
CENTER_NAME = EARTH
REF_FRAME = TOD
TIME_SYSTEM = UTC
COMMENT State Vector
EPOCH = 2021-06-03T00:00:00.000
X = 6655.9942 [km]
Y = -40218.5751 [km]
Z = -82.9177 [km]
X_DOT = 3.11548208 [km/s]
Y_DOT = 0.47042605 [km/s]
Z_DOT = -0.00101495 [km/s]
COMMENT Keplerian elements
SEMI_MAJOR_AXIS = 41399.5123 [km]
ECCENTRICITY = 0.020842611
INCLINATION = 0.117746 [deg]
RA_OF_ASC_NODE = 17.604721 [deg]
ARG_OF_PERICENTER = 218.242943 [deg]
TRUE_ANOMALY = 41.922339 [deg]
GM = 398600.4415 [km**3/s**2]
COMMENT Spacecraft parameters
MASS = 1913.000 [kg]
SOLAR_RAD_AREA = 10.000 [m**2]
SOLAR_RAD_COEFF = 1.300
DRAG_AREA = 10.000 [m**2]
DRAG_COEFF = 2.300
COMMENT 2 planned maneuvers
COMMENT First maneuver: AMF-3
COMMENT Non-impulsive, thrust direction fixed in inertial frame
MAN_EPOCH_IGNITION = 2021-06-03T09:00:34.1
MAN_DURATION = 132.60 [s]
MAN_DELTA_MASS = -18.418 [kg]
MAN_REF_FRAME = EME2000
MAN_DV_1 = -0.02325700 [km/s]
MAN_DV_2 = 0.01683160 [km/s]
MAN_DV_3 = -0.00893444 [km/s]
COMMENT Second maneuver: first station acquisition maneuver
COMMENT impulsive, thrust direction fixed in RTN frame
MAN_EPOCH_IGNITION = 2021-06-05T18:59:21.0
MAN_DURATION = 0.00 [s]
MAN_DELTA_MASS = -1.469 [kg]
MAN_REF_FRAME = RTN
MAN_DV_1 = 0.00101500 [km/s]
MAN_DV_2 = -0.00187300 [km/s]
MAN_DV_3 = 0.00000000 [km/s]
";

#[test]
fn ast_round_trip_gsoc_opm() {
    let parsed = parse(GSOC_OPM).expect("parse");
    let reemitted = format!("{parsed}");
    let reparsed = parse(&reemitted).expect("reparse");
    assert_eq!(parsed, reparsed);
}

#[test]
fn typed_round_trip_gsoc_opm_preserves_structure() {
    // Bit-exact f64 equality through km↔m unit conversions is
    // structurally impossible (each cycle adds sub-ULP noise from the
    // multiply/divide pair). We assert the *structure* round-trips
    // — header fields, metadata, maneuver count, optional-block
    // presence — and rely on the AST round-trip test for byte-faithful
    // wire-level preservation.
    let opm = read_opm(GSOC_OPM).expect("read");
    let written = write_opm(&opm);
    let opm2 = read_opm(&written).expect("re-read");

    assert_eq!(opm.header.originator, opm2.header.originator);
    assert_eq!(opm.header.comments, opm2.header.comments);
    assert_eq!(opm.metadata.object_name, opm2.metadata.object_name);
    assert_eq!(opm.metadata.object_id, opm2.metadata.object_id);
    assert_eq!(opm.metadata.center, opm2.metadata.center);
    assert_eq!(opm.metadata.frame, opm2.metadata.frame);
    assert_eq!(opm.state_comments, opm2.state_comments);
    assert_eq!(opm.maneuvers.len(), opm2.maneuvers.len());
    assert_eq!(opm.keplerian.is_some(), opm2.keplerian.is_some());
    assert_eq!(opm.spacecraft.is_some(), opm2.spacecraft.is_some());
    assert_eq!(opm.covariance.is_some(), opm2.covariance.is_some());
    assert_eq!(opm.user_defined, opm2.user_defined);

    // The Keplerian sub-block's GM round-trips exactly (no unit conv
    // hops — the writer divides by 1e9, reader multiplies by 1e9, and
    // the value 398600.4415 stays bit-exact in f64).
    assert_eq!(
        opm.keplerian.as_ref().unwrap().gm,
        opm2.keplerian.as_ref().unwrap().gm
    );

    // Per-maneuver comment lists round-trip exactly (strings).
    for (a, b) in opm.maneuvers.iter().zip(&opm2.maneuvers) {
        assert_eq!(a.comments, b.comments);
        assert_eq!(a.frame, b.frame);
    }
}

#[test]
fn typed_round_trip_preserves_all_comments() {
    let opm = read_opm(GSOC_OPM).expect("read");

    let header_count = opm.header.comments.len();
    let metadata_count = opm.metadata.comments.len();
    let state_count = opm.state_comments.len();
    let keplerian_count = opm.keplerian.as_ref().map_or(0, |k| k.comments.len());
    let spacecraft_count = opm.spacecraft.as_ref().map_or(0, |s| s.comments.len());
    let covariance_count = opm.covariance.as_ref().map_or(0, |c| c.comments.len());
    let maneuver_count: usize = opm.maneuvers.iter().map(|m| m.comments.len()).sum();

    let total = header_count
        + metadata_count
        + state_count
        + keplerian_count
        + spacecraft_count
        + covariance_count
        + maneuver_count;

    // GSOC fixture has 10 COMMENT lines in the body:
    //   2 in the header (Generated by GSOC, Current intermediate orbit ...)
    //   1 state-vector comment (State Vector)
    //   1 Keplerian comment (Keplerian elements)
    //   1 spacecraft comment (Spacecraft parameters)
    //   3 comments before the first maneuver (2 planned, AMF-3, fixed direction)
    //   2 comments before the second maneuver (Second maneuver, impulsive RTN)
    assert_eq!(
        total, 10,
        "comment counts: header={header_count}, metadata={metadata_count}, state={state_count}, keplerian={keplerian_count}, spacecraft={spacecraft_count}, covariance={covariance_count}, maneuver={maneuver_count}"
    );
}

#[test]
fn gsoc_opm_has_two_maneuvers() {
    let opm = read_opm(GSOC_OPM).expect("read");
    assert_eq!(opm.maneuvers.len(), 2);
}

#[test]
fn gsoc_opm_preserves_user_defined_empty() {
    // The fixture has no USER_DEFINED_* entries — the typed result
    // should mirror that.
    let opm = read_opm(GSOC_OPM).expect("read");
    assert!(opm.user_defined.is_empty());
}
