/*
 * Copyright (c) 2024. Helge Eichhorn and the LOX contributors
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 */

use glam::DVec3;
use pyo3::{
    exceptions::PyValueError,
    pyclass, pymethods,
    types::{PyAnyMethods, PyList},
    Bound, PyErr, PyResult,
};

use lox_bodies::*;
use lox_time::python::ut1::{PyNoOpOffsetProvider, PyUt1Provider};
use lox_time::{python::time::PyTime, ut1::DeltaUt1Tai};
use python::PyBody;

use crate::elements::Keplerian;
use crate::frames::{Icrf, TryToFrame};
use crate::{
    frames::FrameTransformationProvider,
    states::State,
    trajectories::{Trajectory, TrajectoryError},
};

mod generated;

#[pyclass(frozen)]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum PyFrame {
    Icrf,
    Sun,
    Mercury,
    Venus,
    Earth,
    Mars,
    Jupiter,
    Saturn,
    Uranus,
    Neptune,
    Pluto,
    Moon,
    Phobos,
    Deimos,
    Io,
    Europa,
    Ganymede,
    Callisto,
    Amalthea,
    Himalia,
    Elara,
    Pasiphae,
    Sinope,
    Lysithea,
    Carme,
    Ananke,
    Leda,
    Thebe,
    Adrastea,
    Metis,
    Callirrhoe,
    Themisto,
    Magaclite,
    Taygete,
    Chaldene,
    Harpalyke,
    Kalyke,
    Iocaste,
    Erinome,
    Isonoe,
    Praxidike,
    Autonoe,
    Thyone,
    Hermippe,
    Aitne,
    Eurydome,
    Euanthe,
    Euporie,
    Orthosie,
    Sponde,
    Kale,
    Pasithee,
    Hegemone,
    Mneme,
    Aoede,
    Thelxinoe,
    Arche,
    Kallichore,
    Helike,
    Carpo,
    Eukelade,
    Cyllene,
    Kore,
    Herse,
    Dia,
    Mimas,
    Enceladus,
    Tethys,
    Dione,
    Rhea,
    Titan,
    Hyperion,
    Iapetus,
    Phoebe,
    Janus,
    Epimetheus,
    Helene,
    Telesto,
    Calypso,
    Atlas,
    Prometheus,
    Pandora,
    Pan,
    Ymir,
    Paaliaq,
    Tarvos,
    Ijiraq,
    Suttungr,
    Kiviuq,
    Mundilfari,
    Albiorix,
    Skathi,
    Erriapus,
    Siarnaq,
    Thrymr,
    Narvi,
    Methone,
    Pallene,
    Polydeuces,
    Daphnis,
    Aegir,
    Bebhionn,
    Bergelmir,
    Bestla,
    Farbauti,
    Fenrir,
    Fornjot,
    Hati,
    Hyrrokkin,
    Kari,
    Loge,
    Skoll,
    Surtur,
    Anthe,
    Jarnsaxa,
    Greip,
    Tarqeq,
    Aegaeon,
    Ariel,
    Umbriel,
    Titania,
    Oberon,
    Miranda,
    Cordelia,
    Ophelia,
    Bianca,
    Cressida,
    Desdemona,
    Juliet,
    Portia,
    Rosalind,
    Belinda,
    Puck,
    Caliban,
    Sycorax,
    Prospero,
    Setebos,
    Stephano,
    Trinculo,
    Francisco,
    Margaret,
    Ferdinand,
    Perdita,
    Mab,
    Cupid,
    Triton,
    Nereid,
    Naiad,
    Thalassa,
    Despina,
    Galatea,
    Larissa,
    Proteus,
    Halimede,
    Psamathe,
    Sao,
    Laomedeia,
    Neso,
    Charon,
    Nix,
    Hydra,
    Kerberos,
    Styx,
    Gaspra,
    Ida,
    Dactyl,
    Ceres,
    Pallas,
    Vesta,
    Psyche,
    Lutetia,
    Kleopatra,
    Eros,
    Davida,
    Mathilde,
    Steins,
    Braille,
    WilsonHarrington,
    Toutatis,
    Itokawa,
    Bennu,
}

impl FrameTransformationProvider for DeltaUt1Tai {}
impl FrameTransformationProvider for PyNoOpOffsetProvider {}

impl FrameTransformationProvider for PyUt1Provider {}

#[pyclass(name = "State", module = "lox_space", frozen)]
#[derive(Debug, Clone)]
pub struct PyState(pub State<PyTime, PyBody, PyFrame>);

#[pymethods]
impl PyState {
    #[new]
    #[pyo3(signature = (time, position, velocity, origin = "Earth", frame = "ICRF"))]
    fn new(
        time: PyTime,
        position: (f64, f64, f64),
        velocity: (f64, f64, f64),
        origin: &str,
        frame: &str,
    ) -> PyResult<Self> {
        let origin: PyBody = origin.parse()?;
        let frame: PyFrame = frame.parse()?;

        Ok(PyState(State::new(
            time,
            origin,
            frame,
            DVec3::new(position.0, position.1, position.2),
            DVec3::new(velocity.0, velocity.1, velocity.2),
        )))
    }

    fn to_frame(&self, frame: &str, provider: Option<&Bound<'_, PyUt1Provider>>) -> PyResult<Self> {
        let frame: PyFrame = frame.parse()?;
        match frame {
            PyFrame::Icrf => match provider {
                Some(provider) => Ok(PyState(
                    self.try_to_frame(Icrf, provider.get())?
                        .with_frame(PyFrame::Icrf),
                )),
                None => Ok(PyState(
                    self.try_to_frame(Icrf, &PyNoOpOffsetProvider)?
                        .with_frame(PyFrame::Icrf),
                )),
            },
            PyFrame::Sun => todo!(),
            PyFrame::Mercury => todo!(),
            PyFrame::Venus => todo!(),
            PyFrame::Earth => todo!(),
            PyFrame::Mars => todo!(),
            PyFrame::Jupiter => todo!(),
            PyFrame::Saturn => todo!(),
            PyFrame::Uranus => todo!(),
            PyFrame::Neptune => todo!(),
            PyFrame::Pluto => todo!(),
            PyFrame::Moon => todo!(),
            PyFrame::Phobos => todo!(),
            PyFrame::Deimos => todo!(),
            PyFrame::Io => todo!(),
            PyFrame::Europa => todo!(),
            PyFrame::Ganymede => todo!(),
            PyFrame::Callisto => todo!(),
            PyFrame::Amalthea => todo!(),
            PyFrame::Himalia => todo!(),
            PyFrame::Elara => todo!(),
            PyFrame::Pasiphae => todo!(),
            PyFrame::Sinope => todo!(),
            PyFrame::Lysithea => todo!(),
            PyFrame::Carme => todo!(),
            PyFrame::Ananke => todo!(),
            PyFrame::Leda => todo!(),
            PyFrame::Thebe => todo!(),
            PyFrame::Adrastea => todo!(),
            PyFrame::Metis => todo!(),
            PyFrame::Callirrhoe => todo!(),
            PyFrame::Themisto => todo!(),
            PyFrame::Magaclite => todo!(),
            PyFrame::Taygete => todo!(),
            PyFrame::Chaldene => todo!(),
            PyFrame::Harpalyke => todo!(),
            PyFrame::Kalyke => todo!(),
            PyFrame::Iocaste => todo!(),
            PyFrame::Erinome => todo!(),
            PyFrame::Isonoe => todo!(),
            PyFrame::Praxidike => todo!(),
            PyFrame::Autonoe => todo!(),
            PyFrame::Thyone => todo!(),
            PyFrame::Hermippe => todo!(),
            PyFrame::Aitne => todo!(),
            PyFrame::Eurydome => todo!(),
            PyFrame::Euanthe => todo!(),
            PyFrame::Euporie => todo!(),
            PyFrame::Orthosie => todo!(),
            PyFrame::Sponde => todo!(),
            PyFrame::Kale => todo!(),
            PyFrame::Pasithee => todo!(),
            PyFrame::Hegemone => todo!(),
            PyFrame::Mneme => todo!(),
            PyFrame::Aoede => todo!(),
            PyFrame::Thelxinoe => todo!(),
            PyFrame::Arche => todo!(),
            PyFrame::Kallichore => todo!(),
            PyFrame::Helike => todo!(),
            PyFrame::Carpo => todo!(),
            PyFrame::Eukelade => todo!(),
            PyFrame::Cyllene => todo!(),
            PyFrame::Kore => todo!(),
            PyFrame::Herse => todo!(),
            PyFrame::Dia => todo!(),
            PyFrame::Mimas => todo!(),
            PyFrame::Enceladus => todo!(),
            PyFrame::Tethys => todo!(),
            PyFrame::Dione => todo!(),
            PyFrame::Rhea => todo!(),
            PyFrame::Titan => todo!(),
            PyFrame::Hyperion => todo!(),
            PyFrame::Iapetus => todo!(),
            PyFrame::Phoebe => todo!(),
            PyFrame::Janus => todo!(),
            PyFrame::Epimetheus => todo!(),
            PyFrame::Helene => todo!(),
            PyFrame::Telesto => todo!(),
            PyFrame::Calypso => todo!(),
            PyFrame::Atlas => todo!(),
            PyFrame::Prometheus => todo!(),
            PyFrame::Pandora => todo!(),
            PyFrame::Pan => todo!(),
            PyFrame::Ymir => todo!(),
            PyFrame::Paaliaq => todo!(),
            PyFrame::Tarvos => todo!(),
            PyFrame::Ijiraq => todo!(),
            PyFrame::Suttungr => todo!(),
            PyFrame::Kiviuq => todo!(),
            PyFrame::Mundilfari => todo!(),
            PyFrame::Albiorix => todo!(),
            PyFrame::Skathi => todo!(),
            PyFrame::Erriapus => todo!(),
            PyFrame::Siarnaq => todo!(),
            PyFrame::Thrymr => todo!(),
            PyFrame::Narvi => todo!(),
            PyFrame::Methone => todo!(),
            PyFrame::Pallene => todo!(),
            PyFrame::Polydeuces => todo!(),
            PyFrame::Daphnis => todo!(),
            PyFrame::Aegir => todo!(),
            PyFrame::Bebhionn => todo!(),
            PyFrame::Bergelmir => todo!(),
            PyFrame::Bestla => todo!(),
            PyFrame::Farbauti => todo!(),
            PyFrame::Fenrir => todo!(),
            PyFrame::Fornjot => todo!(),
            PyFrame::Hati => todo!(),
            PyFrame::Hyrrokkin => todo!(),
            PyFrame::Kari => todo!(),
            PyFrame::Loge => todo!(),
            PyFrame::Skoll => todo!(),
            PyFrame::Surtur => todo!(),
            PyFrame::Anthe => todo!(),
            PyFrame::Jarnsaxa => todo!(),
            PyFrame::Greip => todo!(),
            PyFrame::Tarqeq => todo!(),
            PyFrame::Aegaeon => todo!(),
            PyFrame::Ariel => todo!(),
            PyFrame::Umbriel => todo!(),
            PyFrame::Titania => todo!(),
            PyFrame::Oberon => todo!(),
            PyFrame::Miranda => todo!(),
            PyFrame::Cordelia => todo!(),
            PyFrame::Ophelia => todo!(),
            PyFrame::Bianca => todo!(),
            PyFrame::Cressida => todo!(),
            PyFrame::Desdemona => todo!(),
            PyFrame::Juliet => todo!(),
            PyFrame::Portia => todo!(),
            PyFrame::Rosalind => todo!(),
            PyFrame::Belinda => todo!(),
            PyFrame::Puck => todo!(),
            PyFrame::Caliban => todo!(),
            PyFrame::Sycorax => todo!(),
            PyFrame::Prospero => todo!(),
            PyFrame::Setebos => todo!(),
            PyFrame::Stephano => todo!(),
            PyFrame::Trinculo => todo!(),
            PyFrame::Francisco => todo!(),
            PyFrame::Margaret => todo!(),
            PyFrame::Ferdinand => todo!(),
            PyFrame::Perdita => todo!(),
            PyFrame::Mab => todo!(),
            PyFrame::Cupid => todo!(),
            PyFrame::Triton => todo!(),
            PyFrame::Nereid => todo!(),
            PyFrame::Naiad => todo!(),
            PyFrame::Thalassa => todo!(),
            PyFrame::Despina => todo!(),
            PyFrame::Galatea => todo!(),
            PyFrame::Larissa => todo!(),
            PyFrame::Proteus => todo!(),
            PyFrame::Halimede => todo!(),
            PyFrame::Psamathe => todo!(),
            PyFrame::Sao => todo!(),
            PyFrame::Laomedeia => todo!(),
            PyFrame::Neso => todo!(),
            PyFrame::Charon => todo!(),
            PyFrame::Nix => todo!(),
            PyFrame::Hydra => todo!(),
            PyFrame::Kerberos => todo!(),
            PyFrame::Styx => todo!(),
            PyFrame::Gaspra => todo!(),
            PyFrame::Ida => todo!(),
            PyFrame::Dactyl => todo!(),
            PyFrame::Ceres => todo!(),
            PyFrame::Pallas => todo!(),
            PyFrame::Vesta => todo!(),
            PyFrame::Psyche => todo!(),
            PyFrame::Lutetia => todo!(),
            PyFrame::Kleopatra => todo!(),
            PyFrame::Eros => todo!(),
            PyFrame::Davida => todo!(),
            PyFrame::Mathilde => todo!(),
            PyFrame::Steins => todo!(),
            PyFrame::Braille => todo!(),
            PyFrame::WilsonHarrington => todo!(),
            PyFrame::Toutatis => todo!(),
            PyFrame::Itokawa => todo!(),
            PyFrame::Bennu => todo!(),
        }
    }
}

#[pyclass(name = "Keplerian", module = "lox_space", frozen)]
pub struct PyKeplerian(pub Keplerian<PyTime, PyBody>);

#[pyclass(name = "Trajectory", module = "lox_space", frozen)]
pub struct PyTrajectory(pub Trajectory<PyTime, PyBody, PyFrame>);

impl From<TrajectoryError> for PyErr {
    fn from(err: TrajectoryError) -> Self {
        PyValueError::new_err(err.to_string())
    }
}

#[pymethods]
impl PyTrajectory {
    #[new]
    fn new(states: &Bound<'_, PyList>) -> PyResult<Self> {
        let states: Vec<PyState> = states.extract()?;
        let states: Vec<State<PyTime, PyBody, PyFrame>> = states.into_iter().map(|s| s.0).collect();
        Ok(PyTrajectory(Trajectory::new(&states)?))
    }
}
