// SPDX-FileCopyrightText: 2026 Helge Eichhorn <git@helgeeichhorn.de>
//
// SPDX-License-Identifier: MPL-2.0

//! Integration tests for the `odm` feature: realistic OPM/OEM fixtures,
//! round-trip serialization, and structural equality checks.

#![cfg(feature = "odm")]

use lox_bodies::DynOrigin;
use lox_core::anomalies::TrueAnomaly;
use lox_core::coords::Cartesian;
use lox_core::elements::Keplerian;
use lox_core::elements::keplerian::{
    ArgumentOfPeriapsis, Eccentricity, Inclination, LongitudeOfAscendingNode, SemiMajorAxis,
};
use lox_core::units::Angle;
use lox_core::units::{Distance, Velocity};
use lox_frames::DynFrame;
use lox_odm::Format;
use lox_odm::types::common::OdmTimeScale;
use lox_orbits::odm::{OmmBuildError, OmmWriteError};
use lox_orbits::orbits::{DynCartesianOrbit, DynKeplerianOrbit, DynTrajectory, Orbit, Trajectory};
use lox_orbits::propagators::sgp4::Sgp4;
use lox_time::deltas::TimeDelta;
use lox_time::time::Time;
use lox_time::time_scales::DynTimeScale;

// ---------------------------------------------------------------------------
// Inline fixtures (KVN form — same wire text used in lox-odm's own tests)
// ---------------------------------------------------------------------------

/// A realistic GSOC-style OPM (Earth-centered, TOD frame, UTC, with
/// Keplerian elements, spacecraft parameters, and two maneuvers).
const GSOC_OPM_KVN: &str = "\
CCSDS_OPM_VERS = 3.0
COMMENT Generated by GSOC
CREATION_DATE = 2021-06-03T05:33:00.123
ORIGINATOR = GSOC
OBJECT_NAME = EUTELSAT W4
OBJECT_ID = 2021-028A
CENTER_NAME = EARTH
REF_FRAME = TOD
TIME_SYSTEM = UTC
EPOCH = 2021-06-03T00:00:00.000
X = 6655.9942 [km]
Y = -40218.5751 [km]
Z = -82.9177 [km]
X_DOT = 3.11548208 [km/s]
Y_DOT = 0.47042605 [km/s]
Z_DOT = -0.00101495 [km/s]
";

/// A realistic JPL multi-segment OEM (Mars Barycenter-centered, J2000 frame, TAI).
const JPL_OEM_KVN: &str = "\
CCSDS_OEM_VERS = 3.0
CREATION_DATE = 1996-11-04T17:22:31
ORIGINATOR = NASA/JPL

META_START
OBJECT_NAME = MARS GLOBAL SURVEYOR
OBJECT_ID = 1996-062A
CENTER_NAME = MARS BARYCENTER
REF_FRAME = J2000
TIME_SYSTEM = TAI
START_TIME = 1996-12-18T12:00:00.331
STOP_TIME = 1996-12-28T21:28:00.331
META_STOP

1996-12-18T12:00:00.331 2789.619 -280.045 -1746.755 4.73372 -2.49586 -1.04195
1996-12-18T12:01:00.331 2783.419 -308.143 -1877.071 5.18604 -2.42124 -1.99608
1996-12-18T12:02:00.331 2776.033 -336.859 -2008.682 5.63678 -2.33951 -1.94687
1996-12-28T21:28:00.331 -3881.024 563.959 -682.773 -3.28827 -3.66735 1.63861

META_START
OBJECT_NAME = MARS GLOBAL SURVEYOR
OBJECT_ID = 1996-062A
CENTER_NAME = MARS BARYCENTER
REF_FRAME = J2000
TIME_SYSTEM = TAI
START_TIME = 1996-12-28T21:29:07.267
STOP_TIME = 1996-12-30T01:28:02.267
META_STOP

1996-12-28T21:29:07.267 -2432.166 -063.042 1742.754 7.33702 -3.495867 -1.041945
1996-12-28T21:59:02.267 -2445.234 -878.141 1873.073 1.86043 -3.421256 -0.996366
1996-12-30T01:28:02.267 2164.375 1115.811 -688.131 -3.53328 -2.88452 0.88535
";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn sample_dyn_orbit() -> DynCartesianOrbit {
    let t = Time::j2000(DynTimeScale::Tai);
    Orbit::from_state(
        Cartesian::new(
            Distance::kilometers(7000.0),
            Distance::kilometers(0.0),
            Distance::kilometers(0.0),
            Velocity::kilometers_per_second(0.0),
            Velocity::kilometers_per_second(7.5),
            Velocity::kilometers_per_second(0.0),
        ),
        t,
        DynOrigin::Earth,
        DynFrame::Icrf,
    )
}

fn sample_dyn_trajectory() -> DynTrajectory {
    let t0 = Time::j2000(DynTimeScale::Tai);
    let t1 = t0 + TimeDelta::from_seconds(60);
    let t2 = t0 + TimeDelta::from_seconds(120);
    let mk = |t, x_km: f64| {
        Orbit::from_state(
            Cartesian::new(
                Distance::kilometers(x_km),
                Distance::kilometers(0.0),
                Distance::kilometers(0.0),
                Velocity::kilometers_per_second(0.0),
                Velocity::kilometers_per_second(7.5),
                Velocity::kilometers_per_second(0.0),
            ),
            t,
            DynOrigin::Earth,
            DynFrame::Icrf,
        )
    };
    Trajectory::new(vec![mk(t0, 7000.0), mk(t1, 6999.0), mk(t2, 6996.0)])
}

// ---------------------------------------------------------------------------
// OPM integration tests
// ---------------------------------------------------------------------------

/// Parse a realistic GSOC OPM KVN fixture and verify the projected orbit's
/// state, origin, and frame.
#[test]
fn gsoc_opm_to_dyn_orbit() {
    let orbit = DynCartesianOrbit::from_opm_str(GSOC_OPM_KVN).unwrap();
    // EARTH center → Earth origin
    assert_eq!(orbit.origin(), DynOrigin::Earth);
    // TOD frame — DynFrame::Tod wraps a ReferenceSystem, so check via the
    // abbreviation string rather than a direct variant comparison.
    assert!(
        matches!(orbit.reference_frame(), DynFrame::Tod(_)),
        "expected a TOD frame, got {:?}",
        orbit.reference_frame()
    );
    // State: position X should be roughly 6655.9942 km (in meters)
    let pos = orbit.position();
    let x_km = pos.x / 1000.0;
    assert!((x_km - 6655.9942).abs() < 0.01, "x_km = {x_km}");
}

/// Round-trip: DynCartesianOrbit → OPM → KVN → re-parse → structural equality.
#[test]
fn dyn_orbit_opm_kvn_round_trip() {
    let orbit = sample_dyn_orbit();
    let kvn = orbit
        .build_opm("TEST-SAT", "2024-IT-001A")
        .originator("INTEGRATION_TEST")
        .write_str(Format::Kvn)
        .unwrap();

    let reparsed = DynCartesianOrbit::from_opm_str(&kvn).unwrap();
    assert_eq!(reparsed.origin(), orbit.origin());
    assert_eq!(reparsed.reference_frame(), orbit.reference_frame());

    // State position/velocity should match to sub-millimetre / sub-mm/s
    let diff_pos = (reparsed.position() - orbit.position()).length();
    let diff_vel = (reparsed.velocity() - orbit.velocity()).length();
    assert!(diff_pos < 0.001, "position diff = {diff_pos} m");
    assert!(diff_vel < 1e-6, "velocity diff = {diff_vel} m/s");
}

/// Same round-trip via XML.
#[test]
fn dyn_orbit_opm_xml_round_trip() {
    let orbit = sample_dyn_orbit();
    let xml = orbit
        .build_opm("TEST-SAT", "2024-IT-001A")
        .originator("INTEGRATION_TEST")
        .write_str(Format::Xml)
        .unwrap();

    let reparsed = DynCartesianOrbit::from_opm_str(&xml).unwrap();
    assert_eq!(reparsed.origin(), orbit.origin());
    assert_eq!(reparsed.reference_frame(), orbit.reference_frame());
    let diff_pos = (reparsed.position() - orbit.position()).length();
    assert!(diff_pos < 0.001, "position diff = {diff_pos} m");
}

// ---------------------------------------------------------------------------
// OEM integration tests
// ---------------------------------------------------------------------------

/// Parse the multi-segment JPL OEM KVN fixture. The first segment should
/// have 4 states; the second should have 3.
#[test]
fn jpl_oem_to_dyn_trajectory_segment_count() {
    let oem = lox_odm::read_oem(JPL_OEM_KVN).unwrap();
    assert_eq!(oem.segments.len(), 2, "expected 2 segments");
    assert_eq!(oem.segments[0].states.len(), 4);
    assert_eq!(oem.segments[1].states.len(), 3);

    // First segment → DynTrajectory via from_oem
    let traj = DynTrajectory::from_oem(&oem).unwrap();
    assert_eq!(traj.origin(), DynOrigin::MarsBarycenter);
    assert_eq!(traj.reference_frame(), DynFrame::J2000);
    assert_eq!(traj.states().len(), 4);
}

/// Round-trip: DynTrajectory → OEM → KVN → re-parse → structural equality.
#[test]
fn dyn_trajectory_oem_kvn_round_trip() {
    let traj = sample_dyn_trajectory();
    let n_states = traj.states().len();
    let origin = traj.origin();
    let frame = traj.reference_frame();
    let kvn = traj
        .build_oem("TEST-SAT", "2024-IT-001A")
        .originator("INTEGRATION_TEST")
        .write_str(Format::Kvn)
        .unwrap();

    let reparsed = DynTrajectory::from_oem_str(&kvn).unwrap();
    assert_eq!(reparsed.origin(), origin);
    assert_eq!(reparsed.reference_frame(), frame);
    assert_eq!(reparsed.states().len(), n_states);
}

/// `from_oem_segment` on a specific segment of a multi-segment OEM.
#[test]
fn from_oem_segment_second_segment() {
    let oem = lox_odm::read_oem(JPL_OEM_KVN).unwrap();
    let seg = &oem.segments[1];
    let traj = DynTrajectory::from_oem_segment(seg).unwrap();
    assert_eq!(traj.states().len(), 3);
    assert_eq!(traj.origin(), DynOrigin::MarsBarycenter);
}

// ---------------------------------------------------------------------------
// Round-trip TIME_SYSTEM preservation (resolves NEW-I2 from review).
// ---------------------------------------------------------------------------

/// Without `.time_system(...)`, a UTC-origin OPM silently widens to TAI on
/// re-emission because the intermediate `DynCartesianOrbit` cannot represent
/// UTC. This baseline is intentionally tested so that any future change to
/// the default conversion path is observable.
#[test]
fn opm_utc_silently_widens_to_tai_without_override() {
    let orbit = DynCartesianOrbit::from_opm_str(GSOC_OPM_KVN).unwrap();
    let kvn = orbit
        .build_opm("EUTELSAT W4", "2021-028A")
        .originator("ROUND_TRIP")
        .write_str(Format::Kvn)
        .unwrap();

    let reparsed = lox_odm::read_opm(&kvn).unwrap();
    // Source was UTC; default round-trip lands in TAI.
    assert_eq!(reparsed.epoch.scale(), OdmTimeScale::Tai);
    assert!(kvn.contains("TIME_SYSTEM = TAI"));
}

/// With `.time_system(OdmTimeScale::Utc)`, the same round-trip preserves the
/// original UTC wire-format. This is the documented escape hatch from the
/// review's NEW-I2 finding.
#[test]
fn opm_time_system_override_preserves_utc() {
    let orbit = DynCartesianOrbit::from_opm_str(GSOC_OPM_KVN).unwrap();
    let kvn = orbit
        .build_opm("EUTELSAT W4", "2021-028A")
        .originator("ROUND_TRIP")
        .time_system(OdmTimeScale::Utc)
        .write_str(Format::Kvn)
        .unwrap();

    let reparsed = lox_odm::read_opm(&kvn).unwrap();
    assert_eq!(reparsed.epoch.scale(), OdmTimeScale::Utc);
    assert!(kvn.contains("TIME_SYSTEM = UTC"), "got:\n{kvn}");

    // EPOCH itself round-trips losslessly under UTC.
    let orig_opm = lox_odm::read_opm(GSOC_OPM_KVN).unwrap();
    assert_eq!(reparsed.epoch, orig_opm.epoch);
}

/// `.time_system(Gps)` re-expresses the orbit's TAI epoch as GPS (TAI−GPS=19s).
#[test]
fn opm_time_system_override_to_gps() {
    let orbit = DynCartesianOrbit::from_opm_str(GSOC_OPM_KVN).unwrap();
    let kvn = orbit
        .build_opm("EUTELSAT W4", "2021-028A")
        .originator("ROUND_TRIP")
        .time_system(OdmTimeScale::Gps)
        .write_str(Format::Kvn)
        .unwrap();

    let reparsed = lox_odm::read_opm(&kvn).unwrap();
    assert_eq!(reparsed.epoch.scale(), OdmTimeScale::Gps);
    assert!(kvn.contains("TIME_SYSTEM = GPS"));
}

/// OEM analogue: trajectory round-trip preserves UTC when `.time_system(Utc)` is set.
#[test]
fn oem_time_system_override_preserves_utc() {
    let kvn = sample_dyn_trajectory()
        .build_oem("TEST-SAT", "2024-IT-001A")
        .originator("ROUND_TRIP")
        .time_system(OdmTimeScale::Utc)
        .write_str(Format::Kvn)
        .unwrap();

    let reparsed = lox_odm::read_oem(&kvn).unwrap();
    let seg = &reparsed.segments[0];
    assert_eq!(seg.metadata.start_time.scale(), OdmTimeScale::Utc);
    assert_eq!(seg.metadata.stop_time.scale(), OdmTimeScale::Utc);
    assert!(kvn.contains("TIME_SYSTEM = UTC"));
}

// ---------------------------------------------------------------------------
// OMM ↔ SGP4 / KeplerianOrbit integration
// ---------------------------------------------------------------------------

/// Realistic Space-Track ISS OMM JSON, matching the wire format clients
/// receive from Space-Track's `/class/gp` endpoint.
const ISS_OMM_JSON: &str = r#"{
    "CCSDS_OMM_VERS": "2.0",
    "CREATION_DATE": "2024-06-18T00:00:00",
    "ORIGINATOR": "18 SPCS",
    "OBJECT_NAME": "ISS (ZARYA)",
    "OBJECT_ID": "1998-067A",
    "CENTER_NAME": "EARTH",
    "REF_FRAME": "TEME",
    "TIME_SYSTEM": "UTC",
    "MEAN_ELEMENT_THEORY": "SGP4",
    "EPOCH": "2024-06-18T09:00:24.214400",
    "MEAN_MOTION": "15.49495945",
    "ECCENTRICITY": "0.0010444",
    "INCLINATION": "51.6410",
    "RA_OF_ASC_NODE": "309.3890",
    "ARG_OF_PERICENTER": "339.5369",
    "MEAN_ANOMALY": "107.8830",
    "EPHEMERIS_TYPE": "0",
    "CLASSIFICATION_TYPE": "U",
    "NORAD_CAT_ID": "25544",
    "ELEMENT_SET_NO": "999",
    "REV_AT_EPOCH": "45873",
    "BSTAR": "0.00030244",
    "MEAN_MOTION_DOT": "0.00016566",
    "MEAN_MOTION_DDOT": "0"
}"#;

/// `Sgp4::from_omm_str` builds a working SGP4 propagator and a one-orbital-
/// period propagation comes back with the same orbital period.
#[test]
fn sgp4_from_omm_str_iss() {
    let sgp4 = Sgp4::from_omm_str(ISS_OMM_JSON).expect("from_omm_str");

    // Propagate to t + one orbital period (≈ 92.82 min from the ISS mean motion).
    let orbital_period = 92.821;
    let t1 = sgp4.time() + TimeDelta::from_minutes_f64(orbital_period);
    let s1 = sgp4.state_at(t1).expect("state_at");
    // Position magnitude should be roughly the orbital radius (~ 6.78 Mm).
    let r = s1.position().length();
    assert!(
        (6_700_000.0..6_900_000.0).contains(&r),
        "unexpected position magnitude: {r} m"
    );
}

/// Round-trip: KeplerianOrbit → OMM → KeplerianOrbit preserves mean elements.
#[test]
fn keplerian_orbit_to_omm_round_trip_iss() {
    let orbit = DynKeplerianOrbit::from_omm_str(ISS_OMM_JSON).expect("from_omm_str");
    let original = orbit.state();
    let kvn = orbit
        .build_omm("ISS (ZARYA)", "1998-067A")
        .originator("ROUND_TRIP")
        .write_str(Format::Kvn)
        .expect("write OMM KVN (ISS is elliptic)");

    let reparsed = lox_odm::read_omm(&kvn).expect("re-parse OMM");
    // Mean elements round-trip via the wire's deg↔rad conversion.
    let me = &reparsed.mean_elements.elements;
    assert!((me.e - original.eccentricity().as_f64()).abs() < 1e-12);
    assert!((me.i - original.inclination().as_f64()).abs() < 1e-12);
    assert!((me.raan - original.longitude_of_ascending_node().as_f64()).abs() < 1e-12);
    assert!((me.aop - original.argument_of_periapsis().as_f64()).abs() < 1e-12);

    // The KeplerianOrbit carries true anomaly; the OMM carries mean
    // anomaly. The builder converts true → mean; on re-read we should
    // get back the same mean anomaly (computed by going round-trip).
    let original_mean = original
        .true_anomaly()
        .to_mean(original.eccentricity())
        .expect("ecc < 1");
    assert!((me.m - original_mean.as_f64()).abs() < 1e-12);

    // No TLE-parameters block: the builder is generic and doesn't fabricate them.
    assert!(reparsed.tle_parameters.is_none());

    // Centre / frame / theory survive the round-trip.
    assert_eq!(reparsed.metadata.mean_element_theory, "SGP/SGP4");
}

/// `DynKeplerianOrbit::from_omm_str` exposes the mean elements as a typed
/// Keplerian view (does *not* claim physical osculating accuracy in TEME).
#[test]
fn dyn_keplerian_orbit_from_omm_iss() {
    let orbit = DynKeplerianOrbit::from_omm_str(ISS_OMM_JSON).expect("from_omm_str");
    assert_eq!(orbit.origin(), DynOrigin::Earth);
    let inc_deg = orbit.inclination().as_f64().to_degrees();
    assert!(
        (inc_deg - 51.6410).abs() < 1e-9,
        "inclination = {inc_deg} deg"
    );
    let ecc = orbit.eccentricity().as_f64();
    assert!((ecc - 0.0010444).abs() < 1e-12, "ecc = {ecc}");
}

/// `OmmBuilder::build` returns a typed error (not a panic) when the
/// orbit is hyperbolic and the true anomaly exceeds the asymptote.
#[test]
fn omm_builder_returns_typed_error_for_hyperbolic_beyond_asymptote() {
    // Hyperbolic orbit (e = 2.0). Asymptote at acos(-1/e) ≈ 120 deg.
    // True anomaly of 170 deg is beyond the asymptote — geometrically
    // impossible — so `to_mean` must fail.
    let ecc = Eccentricity::try_new(2.0).unwrap();
    let kep = Keplerian::new(
        SemiMajorAxis::meters(-1.0e7),
        ecc,
        Inclination::try_new(Angle::radians(0.5)).unwrap(),
        LongitudeOfAscendingNode::try_new(Angle::radians(0.1)).unwrap(),
        ArgumentOfPeriapsis::try_new(Angle::radians(0.2)).unwrap(),
        TrueAnomaly::new(Angle::radians(170.0_f64.to_radians())),
    );
    let orbit: DynKeplerianOrbit = Orbit::from_state(
        kep,
        Time::j2000(DynTimeScale::Tai),
        DynOrigin::Earth,
        DynFrame::Icrf,
    );

    let err = orbit
        .build_omm("HYPER", "2024-HYP-001A")
        .originator("TEST")
        .build()
        .expect_err("hyperbolic build should fail");
    assert!(
        matches!(err, OmmBuildError::Anomaly(_)),
        "expected OmmBuildError::Anomaly, got {err:?}"
    );

    // The fallible `write_str` propagates the same error via OmmWriteError.
    let err = orbit
        .build_omm("HYPER", "2024-HYP-001A")
        .originator("TEST")
        .write_str(Format::Kvn)
        .expect_err("write should fail");
    assert!(
        matches!(err, OmmWriteError::Build(OmmBuildError::Anomaly(_))),
        "expected OmmWriteError::Build(Anomaly), got {err:?}"
    );
}
