[package]
name = "lox-ephem"
version = "0.1.0-alpha.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
nom.workspace = true
lox-utils.workspace = true
