// SPDX-FileCopyrightText: 2026 Helge Eichhorn <git@helgeeichhorn.de>
//
// SPDX-License-Identifier: MPL-2.0

//! Data loading for ITU-R gridded geophysical datasets.
//!
//! Grid data files are stored externally (not embedded in the crate due to size constraints)
//! and loaded from a configurable data directory at runtime.
//!
//! # Data directory resolution
//!
//! The data directory is resolved in this order:
//! 1. `LOX_ITUR_DATA` environment variable
//! 2. `~/.lox/itur-data/`
//!
//! Data is automatically downloaded and converted by the build script.
//!
//! # Binary file format
//!
//! Grid files (`.bin` or `.bin.zst`):
//!   - 6 × f64 LE: lat_start, lat_step, lat_count, lon_start, lon_step, lon_count
//!   - N × f64 LE: row-major data (south-to-north, west-to-east)
//!
//! Table files (`.bin` or `.bin.zst`, e.g. P.676 line data):
//!   - 2 × u64 LE: rows, cols
//!   - rows × cols × f64 LE: row-major data

use std::io::Read;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use thiserror::Error;

use crate::grid::RegularGrid2D;

/// Environment variable for overriding the data directory.
pub const DATA_DIR_ENV: &str = "LOX_ITUR_DATA";

/// Default subdirectory under the user's home directory.
const DEFAULT_DATA_SUBDIR: &str = ".lox/itur-data";

/// Data directory generated by build.rs (baked in at compile time).
const BUILD_DATA_DIR: &str = concat!(env!("OUT_DIR"), "/itur-data");

#[derive(Debug, Error)]
pub enum DataError {
    #[error("I/O error loading {path}: {source}")]
    Io {
        path: PathBuf,
        source: std::io::Error,
    },
    #[error(
        "ITU-R data not found at {path}. \
         Set {env} or run the conversion script. \
         See lox-itur documentation for setup instructions.",
        env = DATA_DIR_ENV
    )]
    DataNotFound { path: PathBuf },
    #[error("invalid grid binary: expected at least 48 header bytes, got {0}")]
    HeaderTooShort(usize),
    #[error("grid data length mismatch: header says {expected} values, got {actual}")]
    GridLengthMismatch { expected: usize, actual: usize },
}

/// Returns the data directory path, resolved in order:
/// 1. `LOX_ITUR_DATA` environment variable
/// 2. Build-time generated data (from `build.rs`)
/// 3. `~/.lox/itur-data/`
pub fn data_dir() -> PathBuf {
    static DIR: OnceLock<PathBuf> = OnceLock::new();
    DIR.get_or_init(|| {
        if let Ok(dir) = std::env::var(DATA_DIR_ENV) {
            return PathBuf::from(dir);
        }
        let build_dir = Path::new(BUILD_DATA_DIR);
        if build_dir.exists() {
            return build_dir.to_owned();
        }
        if let Some(home) = home_dir() {
            home.join(DEFAULT_DATA_SUBDIR)
        } else {
            PathBuf::from(DEFAULT_DATA_SUBDIR)
        }
    })
    .clone()
}

fn home_dir() -> Option<PathBuf> {
    std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
}

// ── Binary parsing ──────────────────────────────────────────────────────────

/// Parses a grid binary blob (uncompressed) into a [`RegularGrid2D`].
pub fn parse_grid(bytes: &[u8]) -> Result<RegularGrid2D, DataError> {
    if bytes.len() < 48 {
        return Err(DataError::HeaderTooShort(bytes.len()));
    }

    let lat_start = f64::from_le_bytes(bytes[0..8].try_into().unwrap());
    let lat_step = f64::from_le_bytes(bytes[8..16].try_into().unwrap());
    let lat_count = f64::from_le_bytes(bytes[16..24].try_into().unwrap()) as usize;
    let lon_start = f64::from_le_bytes(bytes[24..32].try_into().unwrap());
    let lon_step = f64::from_le_bytes(bytes[32..40].try_into().unwrap());
    let lon_count = f64::from_le_bytes(bytes[40..48].try_into().unwrap()) as usize;

    let expected = lat_count * lon_count;
    let data_bytes = &bytes[48..];
    let actual = data_bytes.len() / 8;
    if actual != expected {
        return Err(DataError::GridLengthMismatch { expected, actual });
    }

    let data: Vec<f64> = data_bytes
        .chunks_exact(8)
        .map(|chunk| f64::from_le_bytes(chunk.try_into().unwrap()))
        .collect();

    Ok(RegularGrid2D::new(
        lat_start, lat_step, lat_count, lon_start, lon_step, lon_count, data,
    ))
}

// ── Decompression ───────────────────────────────────────────────────────────

fn decompress_zstd(compressed: &[u8]) -> Result<Vec<u8>, DataError> {
    let mut decoder = zstd::Decoder::new(compressed).map_err(|e| DataError::Io {
        path: PathBuf::from("<zstd>"),
        source: e,
    })?;
    let mut buf = Vec::new();
    decoder.read_to_end(&mut buf).map_err(|e| DataError::Io {
        path: PathBuf::from("<zstd>"),
        source: e,
    })?;
    Ok(buf)
}

/// Decompresses zstd-compressed bytes, then parses as a grid.
pub fn decompress_and_parse_grid(compressed: &[u8]) -> Result<RegularGrid2D, DataError> {
    let decompressed = decompress_zstd(compressed)?;
    parse_grid(&decompressed)
}

// ── File loading ────────────────────────────────────────────────────────────

fn load_bytes(path: &Path) -> Result<Vec<u8>, DataError> {
    if !path.exists() {
        return Err(DataError::DataNotFound {
            path: path.to_owned(),
        });
    }
    std::fs::read(path).map_err(|e| DataError::Io {
        path: path.to_owned(),
        source: e,
    })
}

/// Loads a grid from a file on disk (supports both `.bin` and `.bin.zst`).
pub fn load_grid_from_file(path: &Path) -> Result<RegularGrid2D, DataError> {
    let bytes = load_bytes(path)?;
    if path.extension().is_some_and(|ext| ext == "zst") {
        decompress_and_parse_grid(&bytes)
    } else {
        parse_grid(&bytes)
    }
}

/// Loads a grid from the data directory by relative path (e.g. `"1511/v2_topo.bin.zst"`).
pub fn load_grid(relative_path: &str) -> Result<RegularGrid2D, DataError> {
    let path = data_dir().join(relative_path);
    load_grid_from_file(&path)
}

// ── Lazy file-based grid ────────────────────────────────────────────────────

/// A lazily-loaded grid that reads from the data directory on first access.
pub struct LazyGrid {
    cell: OnceLock<RegularGrid2D>,
    relative_path: &'static str,
}

impl LazyGrid {
    /// Creates a new lazy grid that will load from `relative_path` within the data directory.
    pub const fn new(relative_path: &'static str) -> Self {
        Self {
            cell: OnceLock::new(),
            relative_path,
        }
    }

    /// Returns a reference to the grid, loading from disk on first call.
    ///
    /// # Panics
    ///
    /// Panics if the data file is missing or invalid.
    pub fn get(&self) -> &RegularGrid2D {
        self.cell
            .get_or_init(|| load_grid(self.relative_path).expect("failed to load ITU-R data"))
    }
}

#[cfg(test)]
mod tests {
    use lox_test_utils::assert_approx_eq;

    use super::*;

    #[test]
    fn test_round_trip_grid() {
        let lat_start: f64 = -10.0;
        let lat_step: f64 = 10.0;
        let lat_count: f64 = 3.0;
        let lon_start: f64 = 0.0;
        let lon_step: f64 = 10.0;
        let lon_count: f64 = 4.0;
        let values: Vec<f64> = vec![
            1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0,
        ];

        let mut bytes = Vec::new();
        for &v in &[
            lat_start, lat_step, lat_count, lon_start, lon_step, lon_count,
        ] {
            bytes.extend_from_slice(&v.to_le_bytes());
        }
        for &v in &values {
            bytes.extend_from_slice(&v.to_le_bytes());
        }

        let grid = parse_grid(&bytes).unwrap();
        assert_approx_eq!(grid.bilinear(0.0, 10.0), 6.0, atol <= 1e-12);
    }

    #[test]
    fn test_parse_grid_header_too_short() {
        let err = parse_grid(&[0u8; 10]).unwrap_err();
        assert!(matches!(err, DataError::HeaderTooShort(10)));
    }

    #[test]
    fn test_parse_grid_length_mismatch() {
        // Header says 2x2=4 values but provide only 2
        let mut bytes = Vec::new();
        for &v in &[0.0_f64, 1.0, 2.0, 0.0, 1.0, 2.0] {
            bytes.extend_from_slice(&v.to_le_bytes());
        }
        // Only 2 data values instead of 4
        bytes.extend_from_slice(&1.0_f64.to_le_bytes());
        bytes.extend_from_slice(&2.0_f64.to_le_bytes());
        let err = parse_grid(&bytes).unwrap_err();
        assert!(matches!(err, DataError::GridLengthMismatch { .. }));
    }

    #[test]
    fn test_load_grid_missing_file() {
        let err = load_grid("nonexistent/file.bin.zst").unwrap_err();
        assert!(matches!(err, DataError::DataNotFound { .. }));
    }

    #[test]
    fn test_data_dir_from_env() {
        let _dir = data_dir();
    }
}
