[package]
name = "lox-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
fast_polynomial.workspace = true
float_eq.workspace = true
glam.workspace = true
thiserror.workspace = true

[dev-dependencies]
rstest.workspace = true
