[package]
name = "lox-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
fast_polynomial.workspace = true
nalgebra.workspace = true
thiserror.workspace = true

[dev-dependencies]
float_eq.workspace = true
rstest.workspace = true
