[package]
name = "lox-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
fast_polynomial.workspace = true
thiserror.workspace = true
nom = "7.1.3"
fast_polynomial = "0.1.0"
quick-xml = { version = "0.31.0", features = ["serde"] }
serde = { version = "1.0.194", features = ["serde_derive"] }
serde_json = "1.0.113"
error = "0.1.9"

[dev-dependencies]
float_eq.workspace = true
rstest.workspace = true
