[package]
name = "lox_time"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
num = "0.4.1"
float_eq.workspace = true
mockall = "0.12.1"

[dev-dependencies]
proptest.workspace = true
rstest.workspace = true
