// Auto-generated by `lox_gen`. Do not edit!
use super::{NaifId, PointMass};
pub struct SolarSystemBarycenter;
impl NaifId for SolarSystemBarycenter {
    fn id() -> i32 {
        0i32
    }
}
pub struct MercuryBarycenter;
impl NaifId for MercuryBarycenter {
    fn id() -> i32 {
        1i32
    }
}
impl PointMass for MercuryBarycenter {
    fn gravitational_parameter() -> f64 {
        22031.868551400003f64
    }
}
pub struct VenusBarycenter;
impl NaifId for VenusBarycenter {
    fn id() -> i32 {
        2i32
    }
}
impl PointMass for VenusBarycenter {
    fn gravitational_parameter() -> f64 {
        324858.592f64
    }
}
pub struct EarthBarycenter;
impl NaifId for EarthBarycenter {
    fn id() -> i32 {
        3i32
    }
}
impl PointMass for EarthBarycenter {
    fn gravitational_parameter() -> f64 {
        403503.2356254802f64
    }
}
pub struct MarsBarycenter;
impl NaifId for MarsBarycenter {
    fn id() -> i32 {
        4i32
    }
}
impl PointMass for MarsBarycenter {
    fn gravitational_parameter() -> f64 {
        42828.3758157561f64
    }
}
pub struct JupiterBarycenter;
impl NaifId for JupiterBarycenter {
    fn id() -> i32 {
        5i32
    }
}
impl PointMass for JupiterBarycenter {
    fn gravitational_parameter() -> f64 {
        126712764.09999998f64
    }
}
pub struct SaturnBarycenter;
impl NaifId for SaturnBarycenter {
    fn id() -> i32 {
        6i32
    }
}
impl PointMass for SaturnBarycenter {
    fn gravitational_parameter() -> f64 {
        37940584.8418f64
    }
}
pub struct UranusBarycenter;
impl NaifId for UranusBarycenter {
    fn id() -> i32 {
        7i32
    }
}
impl PointMass for UranusBarycenter {
    fn gravitational_parameter() -> f64 {
        5794556.3999999985f64
    }
}
pub struct NeptuneBarycenter;
impl NaifId for NeptuneBarycenter {
    fn id() -> i32 {
        8i32
    }
}
impl PointMass for NeptuneBarycenter {
    fn gravitational_parameter() -> f64 {
        6836527.100580399f64
    }
}
pub struct PlutoBarycenter;
impl NaifId for PlutoBarycenter {
    fn id() -> i32 {
        9i32
    }
}
impl PointMass for PlutoBarycenter {
    fn gravitational_parameter() -> f64 {
        975.5f64
    }
}
