[package]
name = "lox-gen"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
lox-io = { path = "../../crates/lox-io" }

lazy_static = "1.4.0"
proc-macro2 = "1.0.78"
quote = "1.0.35"
thiserror = "1.0.57"
