[package]
name = "lox-gen"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
lox-io = { path = "../../crates/lox-io" }

proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.90"
prettyplease = "0.2.25"
