# SPDX-FileCopyrightText: 2024 Helge Eichhorn <git@helgeeichhorn.de>
#
# SPDX-License-Identifier: MPL-2.0

[package]
name = "lox-gen"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
lox-io = { path = "../../crates/lox-io" }

proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.90"
prettyplease = "0.2.25"
