[package]
name = "lox_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lox_io = { path = "../../crates/lox_io" }

lazy_static = "1.4.0"
proc-macro2 = "1.0"
quote = "1.0"
thiserror = "1.0.50"
