# SPDX-FileCopyrightText: 2024 Helge Eichhorn <git@helgeeichhorn.de>
#
# SPDX-License-Identifier: MPL-2.0

[package]
name = "lox-gen"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
lox-io = { path = "../../crates/lox-io" }

prettyplease = "0.2.37"
proc-macro2 = "1.0.103"
quote = "1.0.41"
syn = "2.0.108"
